name: Generate Audio (Full or Sample)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose which version to generate'
        required: true
        default: 'sample'
        type: choice
        options:
        - sample
        - full

jobs:
  build_audio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python libraries
      run: pip install -r requirements.txt

    - name: Run Sample Generator
      if: ${{ github.event.inputs.version == 'sample' }}
      run: python sample.py

    - name: Run Full Generator
      if: ${{ github.event.inputs.version == 'full' }}
      run: python main.py

    - name: Upload Audio Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.version }}-audio-files
        path: |
          *.wav
          *.mp3
        retention-days: 5
